ACCESS_KEY : "AKIAYU3X4QOD57E6TNFU"
SECRET_KEY : "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"
SOURCE_BUCKET : "sourcebucketdls"
RAW_BUCKET : "rawlayerdls"
LOG_BUCKET : "errorlogdls"
HOST : "test-mad.cbeu9dz56fde.us-east-1.redshift.amazonaws.com"
DATABASE : "dev"
USER : "awsuser"
PASSWORD : "Password4321"
SCHEMA_PATH : "schema"